# Generated by Django 4.2.6 on 2024-01-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productcategorymodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='breif_description',
        ),
    ]
