# Generated by Django 4.2.6 on 2024-01-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productmodel_discount_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='breif_description',
            new_name='brief_description',
        ),
    ]
