# Generated by Django 4.2.6 on 2024-01-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_ordermodel_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='coupon',
        ),
    ]
