# Generated by Django 4.2.6 on 2024-01-16 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_ordermodel_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.couponmodel'),
        ),
    ]
