# Generated by Django 4.2.6 on 2024-01-16 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0009_alter_couponmodel_used_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='coupon_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
