# Generated by Django 4.2.6 on 2024-01-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField()),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('ref_id', models.BigIntegerField()),
                ('response_code', models.IntegerField()),
                ('response_json', models.JSONField(default=dict)),
                ('status', models.IntegerField(choices=[(1, 'در انتظار وضعیت'), (2, 'موفق'), (3, 'نا موفق')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
