# Generated by Django 4.2.6 on 2024-01-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_ordermodel_payment_alter_ordermodel_status'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentModel',
        ),
    ]
